const bibles = `1:1\tIn the days when the judges ruled in Israel, a severe famine came upon the land. So a man from Bethlehem in Judah left his home and went to live in the country of Moab, taking his wife and two sons with him.\tDu temps des juges, il y eut une famine dans le pays. Un homme de Bethléhem de Juda partit, avec sa femme et ses deux fils, pour faire un séjour dans le pays de Moab.
1:2\tThe man’s name was Elimelech, and his wife was Naomi. Their two sons were Mahlon and Kilion. They were Ephrathites from Bethlehem in the land of Judah. And when they reached Moab, they settled there.\tLe nom de cet homme était Élimélec, celui de sa femme Naomi, et ses deux fils s'appelaient Machlon et Kiljon; ils étaient Éphratiens, de Bethléhem de Juda. Arrivés au pays de Moab, ils y fixèrent leur demeure.
1:3\tThen Elimelech died, and Naomi was left with her two sons.\tÉlimélec, mari de Naomi, mourut, et elle resta avec ses deux fils.
1:4\tThe two sons married Moabite women. One married a woman named Orpah, and the other a woman named Ruth. But about ten years later,\tIls prirent des femmes Moabites, dont l'une se nommait Orpa, et l'autre Ruth, et ils habitèrent là environ dix ans.
1:5\tboth Mahlon and Kilion died. This left Naomi alone, without her two sons or her husband.\tMachlon et Kiljon moururent aussi tous les deux, et Naomi resta privée de ses deux fils et de son mari.
1:6\tThen Naomi heard in Moab that the Lord had blessed his people in Judah by giving them good crops again. So Naomi and her daughters-in-law got ready to leave Moab to return to her homeland.\tPuis elle se leva, elle et ses belles-filles, afin de quitter le pays de Moab, car elle apprit au pays de Moab que l'Éternel avait visité son peuple et lui avait donné du pain.
1:7\tWith her two daughters-in-law she set out from the place where she had been living, and they took the road that would lead them back to Judah.\tElle sortit du lieu qu'elle habitait, accompagnée de ses deux belles-filles, et elle se mit en route pour retourner dans le pays de Juda.
1:8\tBut on the way, Naomi said to her two daughters-in-law, “Go back to your mothers’ homes. And may the Lord reward you for your kindness to your husbands and to me.\tNaomi dit alors à ses deux belles-filles: Allez, retournez chacune à la maison de sa mère! Que l'Éternel use de bonté envers vous, comme vous l'avez fait envers ceux qui sont morts et envers moi!
1:9\tMay the Lord bless you with the security of another marriage.” Then she kissed them good-bye, and they all broke down and wept.\tQue l'Éternel vous fasse trouver à chacune du repos dans la maison d'un mari! Et elle les baisa. Elles élevèrent la voix, et pleurèrent;
1:10\t“No,” they said. “We want to go with you to your people.”\tet elles lui dirent: Non, nous irons avec toi vers ton peuple.
1:11\tBut Naomi replied, “Why should you go on with me? Can I still give birth to other sons who could grow up to be your husbands?\tNaomi, dit: Retournez, mes filles! Pourquoi viendriez-vous avec moi? Ai-je encore dans mon sein des fils qui puissent devenir vos maris?
1:12\tNo, my daughters, return to your parents’ homes, for I am too old to marry again. And even if it were possible, and I were to get married tonight and bear sons, then what?\tRetournez, mes filles, allez! Je suis trop vieille pour me remarier. Et quand je dirais: J'ai de l'espérance; quand cette nuit même je serais avec un mari, et que j'enfanterais des fils,
1:13\tWould you wait for them to grow up and refuse to marry someone else? No, of course not, my daughters! Things are far more bitter for me than for you, because the Lord himself has raised his fist against me.”\tattendriez-vous pour cela qu'ils eussent grandi, refuseriez-vous pour cela de vous marier? Non, mes filles! car à cause de vous je suis dans une grande affliction de ce que la main de l'Éternel s'est étendue contre moi.
1:14\tAnd again they wept together, and Orpah kissed her mother-in-law good-bye. But Ruth clung tightly to Naomi.\tEt elles élevèrent la voix, et pleurèrent encore. Orpa baisa sa belle-mère, mais Ruth s'attacha à elle.
1:15\t“Look,” Naomi said to her, “your sister-in-law has gone back to her people and to her gods. You should do the same.”\tNaomi dit à Ruth: Voici, ta belle-soeur est retournée vers son peuple et vers ses dieux; retourne, comme ta belle-soeur.
1:16\tBut Ruth replied, “Don’t ask me to leave you and turn back. Wherever you go, I will go; wherever you live, I will live. Your people will be my people, and your God will be my God.\tRuth répondit: Ne me presse pas de te laisser, de retourner loin de toi! Où tu iras j'irai, où tu demeureras je demeurerai; ton peuple sera mon peuple, et ton Dieu sera mon Dieu;
1:17\tWherever you die, I will die, and there I will be buried. May the Lord punish me severely if I allow anything but death to separate us!”\toù tu mourras je mourrai, et j'y serai enterrée. Que l'Éternel me traite dans toute sa rigueur, si autre chose que la mort vient à me séparer de toi!
1:18\tWhen Naomi saw that Ruth was determined to go with her, she said nothing more.\tNaomi, la voyant décidée à aller avec elle, cessa ses instances.
1:19\tSo the two of them continued on their journey. When they came to Bethlehem, the entire town was excited by their arrival. “Is it really Naomi?” the women asked.\tElles firent ensemble le voyage jusqu'à leur arrivée à Bethléhem. Et lorsqu'elles entrèrent dans Bethléhem, toute la ville fut émue à cause d'elles, et les femmes disaient: Est-ce là Naomi?
1:20\t“Don’t call me Naomi,” she responded. “Instead, call me Mara, for the Almighty has made life very bitter for me.\tElle leur dit: Ne m'appelez pas Naomi; appelez-moi Mara, car le Tout-Puissant m'a remplie d'amertume.
1:21\tI went away full, but the Lord has brought me home empty. Why call me Naomi when the Lord has caused me to suffer and the Almighty has sent such tragedy upon me?”\tJ'étais dans l'abondance à mon départ, et l'Éternel me ramène les mains vides. Pourquoi m'appelleriez-vous Naomi, après que l'Éternel s'est prononcé contre moi, et que le Tout-Puissant m'a affligée?
1:22\tSo Naomi returned from Moab, accompanied by her daughter-in-law Ruth, the young Moabite woman. They arrived in Bethlehem in late spring, at the beginning of the barley harvest.\tAinsi revinrent du pays de Moab Naomi et sa belle-fille, Ruth la Moabite. Elles arrivèrent à Bethléhem au commencement de la moisson des orges.
2:1\tNow there was a wealthy and influential man in Bethlehem named Boaz, who was a relative of Naomi’s husband, Elimelech.\tNaomi avait un parent de son mari. C'était un homme puissant et riche, de la famille d'Élimélec, et qui se nommait Boaz.
2:2\tOne day Ruth the Moabite said to Naomi, “Let me go out into the harvest fields to pick up the stalks of grain left behind by anyone who is kind enough to let me do it.” Naomi replied, “All right, my daughter, go ahead.”\tRuth la Moabite dit à Naomi: Laisse-moi, je te prie, aller glaner des épis dans le champ de celui aux yeux duquel je trouverai grâce. Elle lui répondit: Va, ma fille.
2:3\tSo Ruth went out to gather grain behind the harvesters. And as it happened, she found herself working in a field that belonged to Boaz, the relative of her father-in-law, Elimelech.\tElle alla glaner dans un champ, derrière les moissonneurs. Et il se trouva par hasard que la pièce de terre appartenait à Boaz, qui était de la famille d'Élimélec.
2:4\tWhile she was there, Boaz arrived from Bethlehem and greeted the harvesters. “The Lord be with you!” he said. “The Lord bless you!” the harvesters replied.\tEt voici, Boaz vint de Bethléhem, et il dit aux moissonneurs: Que l'Éternel soit avec vous! Ils lui répondirent: Que l'Éternel te bénisse!
2:5\tThen Boaz asked his foreman, “Who is that young woman over there? Who does she belong to?”\tEt Boaz dit à son serviteur chargé de surveiller les moissonneurs: À qui est cette jeune femme?
2:6\tAnd the foreman replied, “She is the young woman from Moab who came back with Naomi.\tLe serviteur chargé de surveiller les moissonneurs répondit: C'est une jeune femme Moabite, qui est revenue avec Naomi du pays de Moab.
2:7\tShe asked me this morning if she could gather grain behind the harvesters. She has been hard at work ever since, except for a few minutes’ rest in the shelter.”\tElle a dit: Permettez-moi de glaner et de ramasser des épis entre les gerbes, derrière les moissonneurs. Et depuis ce matin qu'elle est venue, elle a été debout jusqu'à présent, et ne s'est reposée qu'un moment dans la maison.
2:8\tBoaz went over and said to Ruth, “Listen, my daughter. Stay right here with us when you gather grain; don’t go to any other fields. Stay right behind the young women working in my field.\tBoaz dit à Ruth: Écoute, ma fille, ne va pas glaner dans un autre champ; ne t'éloigne pas d'ici, et reste avec mes servantes.
2:9\tSee which part of the field they are harvesting, and then follow them. I have warned the young men not to treat you roughly. And when you are thirsty, help yourself to the water they have drawn from the well.”\tRegarde où l'on moissonne dans le champ, et va après elles. J'ai défendu à mes serviteurs de te toucher. Et quand tu auras soif, tu iras aux vases, et tu boiras de ce que les serviteurs auront puisé.
2:10\tRuth fell at his feet and thanked him warmly. “What have I done to deserve such kindness?” she asked. “I am only a foreigner.”\tAlors elle tomba sur sa face et se prosterna contre terre, et elle lui dit: Comment ai-je trouvé grâce à tes yeux, pour que tu t'intéresses à moi, à moi qui suis une étrangère?
2:11\t“Yes, I know,” Boaz replied. “But I also know about everything you have done for your mother-in-law since the death of your husband. I have heard how you left your father and mother and your own land to live here among complete strangers.\tBoaz lui répondit: On m'a rapporté tout ce que tu as fait pour ta belle-mère depuis la mort de ton mari, et comment tu as quitté ton père et ta mère et le pays de ta naissance, pour aller vers un peuple que tu ne connaissais point auparavant.
2:12\tMay the Lord, the God of Israel, under whose wings you have come to take refuge, reward you fully for what you have done.”\tQue l'Éternel te rende ce que tu as fait, et que ta récompense soit entière de la part de l'Éternel, le Dieu d'Israël, sous les ailes duquel tu es venue te réfugier!
2:13\t“I hope I continue to please you, sir,” she replied. “You have comforted me by speaking so kindly to me, even though I am not one of your workers.”\tEt elle dit: Oh! que je trouve grâce à tes yeux, mon seigneur! Car tu m'as consolée, et tu as parlé au coeur de ta servante. Et pourtant je ne suis pas, moi, comme l'une de tes servantes.
2:14\tAt mealtime Boaz called to her, “Come over here, and help yourself to some food. You can dip your bread in the sour wine.” So she sat with his harvesters, and Boaz gave her some roasted grain to eat. She ate all she wanted and still had some left over.\tAu moment du repas, Boaz dit à Ruth: Approche, mange du pain, et trempe ton morceau dans le vinaigre. Elle s'assit à côté des moissonneurs. On lui donna du grain rôti; elle mangea et se rassasia, et elle garda le reste.
2:15\tWhen Ruth went back to work again, Boaz ordered his young men, “Let her gather grain right among the sheaves without stopping her.\tPuis elle se leva pour glaner. Boaz donna cet ordre à ses serviteurs: Qu'elle glane aussi entre les gerbes, et ne l'inquiétez pas,
2:16\tAnd pull out some heads of barley from the bundles and drop them on purpose for her. Let her pick them up, and don’t give her a hard time!”\tet même vous ôterez pour elle des gerbes quelques épis, que vous la laisserez glaner, sans lui faire de reproches.
2:17\tSo Ruth gathered barley there all day, and when she beat out the grain that evening, it filled an entire basket.\tElle glana dans le champ jusqu'au soir, et elle battit ce qu'elle avait glané. Il y eut environ un épha d'orge.
2:18\tShe carried it back into town and showed it to her mother-in-law. Ruth also gave her the roasted grain that was left over from her meal.\tElle l'emporta et rentra dans la ville, et sa belle-mère vit ce qu'elle avait glané. Elle sortit aussi les restes de son repas, et les lui donna.
2:19\t“Where did you gather all this grain today?” Naomi asked. “Where did you work? May the Lord bless the one who helped you!” So Ruth told her mother-in-law about the man in whose field she had worked. She said, “The man I worked with today is named Boaz.”\tSa belle-mère lui dit: Où as-tu glané aujourd'hui, et où as-tu travaillé? Béni soit celui qui s'est intéressé à toi! Et Ruth fit connaître à sa belle-mère chez qui elle avait travaillé: L'homme chez qui j'ai travaillé aujourd'hui, dit-elle, s'appelle Boaz.
2:20\t“May the Lord bless him!” Naomi told her daughter-in-law. “He is showing his kindness to us as well as to your dead husband. That man is one of our closest relatives, one of our family redeemers.”\tNaomi dit à sa belle-fille: Qu'il soit béni de l'Éternel, qui se montre miséricordieux pour les vivants comme il le fut pour ceux qui sont morts! Cet homme est notre parent, lui dit encore Naomi, il est de ceux qui ont sur nous droit de rachat.
2:21\tThen Ruth said, “What’s more, Boaz even told me to come back and stay with his harvesters until the entire harvest is completed.”\tRuth la Moabite ajouta: Il m'a dit aussi: Reste avec mes serviteurs, jusqu'à ce qu'ils aient achevé toute ma moisson.
2:22\t“Good!” Naomi exclaimed. “Do as he said, my daughter. Stay with his young women right through the whole harvest. You might be harassed in other fields, but you’ll be safe with him.”\tEt Naomi dit à Ruth, sa belle-fille: Il est bon, ma fille, que tu sortes avec ses servantes, et qu'on ne te rencontre pas dans un autre champ.
2:23\tSo Ruth worked alongside the women in Boaz’s fields and gathered grain with them until the end of the barley harvest. Then she continued working with them through the wheat harvest in early summer. And all the while she lived with her mother-in-law.\tElle resta donc avec les servantes de Boaz, pour glaner, jusqu'à la fin de la moisson des orges et de la moisson du froment. Et elle demeurait avec sa belle-mère.
3:1\tOne day Naomi said to Ruth, “My daughter, it’s time that I found a permanent home for you, so that you will be provided for.\tNaomi, sa belle-mère, lui dit: Ma fille, je voudrais assurer ton repos, afin que tu fusses heureuse.
3:2\tBoaz is a close relative of ours, and he’s been very kind by letting you gather grain with his young women. Tonight he will be winnowing barley at the threshing floor.\tEt maintenant Boaz, avec les servantes duquel tu as été, n'est-il pas notre parent? Voici, il doit vanner cette nuit les orges qui sont dans l'aire.
3:3\tNow do as I tell you—take a bath and put on perfume and dress in your nicest clothes. Then go to the threshing floor, but don’t let Boaz see you until he has finished eating and drinking.\tLave-toi et oins-toi, puis remets tes habits, et descends à l'aire. Tu ne te feras pas connaître à lui, jusqu'à ce qu'il ait achevé de manger et de boire.
3:4\tBe sure to notice where he lies down; then go and uncover his feet and lie down there. He will tell you what to do.”\tEt quand il ira se coucher, observe le lieu où il se couche. Ensuite va, découvre ses pieds, et couche-toi. Il te dira lui-même ce que tu as à faire.
3:5\t“I will do everything you say,” Ruth replied.\tElle lui répondit: Je ferai tout ce que tu as dit.
3:6\tSo she went down to the threshing floor that night and followed the instructions of her mother-in-law.\tElle descendit à l'aire, et fit tout ce qu'avait ordonné sa belle-mère.
3:7\tAfter Boaz had finished eating and drinking and was in good spirits, he lay down at the far end of the pile of grain and went to sleep. Then Ruth came quietly, uncovered his feet, and lay down.\tBoaz mangea et but, et son coeur était joyeux. Il alla se coucher à l'extrémité d'un tas de gerbes. Ruth vint alors tout doucement, découvrit ses pieds, et se coucha.
3:8\tAround midnight Boaz suddenly woke up and turned over. He was surprised to find a woman lying at his feet!\tAu milieu de la nuit, cet homme eut une frayeur; il se pencha, et voici, une femme était couchée à ses pieds.
3:9\t“Who are you?” he asked. “I am your servant Ruth,” she replied. “Spread the corner of your covering over me, for you are my family redeemer.”\tIl dit: Qui es-tu? Elle répondit: Je suis Ruth, ta servante; étends ton aile sur ta servante, car tu as droit de rachat.
3:10\t“The Lord bless you, my daughter!” Boaz exclaimed. “You are showing even more family loyalty now than you did before, for you have not gone after a younger man, whether rich or poor.\tEt il dit: Sois bénie de l'Éternel, ma fille! Ce dernier trait témoigne encore plus en ta faveur que le premier, car tu n'as pas recherché des jeunes gens, pauvres ou riches.
3:11\tNow don’t worry about a thing, my daughter. I will do what is necessary, for everyone in town knows you are a virtuous woman.\tMaintenant, ma fille, ne crains point; je ferai pour toi tout ce que tu diras; car toute la porte de mon peuple sait que tu es une femme vertueuse.
3:12\tBut while it’s true that I am one of your family redeemers, there is another man who is more closely related to you than I am.\tIl est bien vrai que j'ai droit de rachat, mais il en existe un autre plus proche que moi.
3:13\tStay here tonight, and in the morning I will talk to him. If he is willing to redeem you, very well. Let him marry you. But if he is not willing, then as surely as the Lord lives, I will redeem you myself! Now lie down here until morning.”\tPasse ici la nuit. Et demain, s'il veut user envers toi du droit de rachat, à la bonne heure, qu'il le fasse; mais s'il ne lui plaît pas d'en user envers toi, j'en userai, moi, l'Éternel est vivant! Reste couchée jusqu'au matin.
3:14\tSo Ruth lay at Boaz’s feet until the morning, but she got up before it was light enough for people to recognize each other. For Boaz had said, “No one must know that a woman was here at the threshing floor.”\tElle resta couchée à ses pieds jusqu'au matin, et elle se leva avant qu'on pût se reconnaître l'un l'autre. Boaz dit: Qu'on ne sache pas qu'une femme est entrée dans l'aire.
3:15\tThen Boaz said to her, “Bring your cloak and spread it out.” He measured six scoops of barley into the cloak and placed it on her back. Then he returned to the town.\tEt il ajouta: Donne le manteau qui est sur toi, et tiens-le. Elle le tint, et il mesura six mesures d'orge, qu'il chargea sur elle. Puis il rentra dans la ville.
3:16\tWhen Ruth went back to her mother-in-law, Naomi asked, “What happened, my daughter?” Ruth told Naomi everything Boaz had done for her,\tRuth revint auprès de sa belle-mère, et Naomi dit: Est-ce toi, ma fille? Ruth lui raconta tout ce que cet homme avait fait pour elle.
3:17\tand she added, “He gave me these six scoops of barley and said, ‘Don’t go back to your mother-in-law empty-handed.’”\tElle dit: Il m'a donné ces six mesures d'orge, en disant: Tu ne retourneras pas à vide vers ta belle-mère.
3:18\tThen Naomi said to her, “Just be patient, my daughter, until we hear what happens. The man won’t rest until he has settled things today.”\tEt Naomi dit: Sois tranquille, ma fille, jusqu'à ce que tu saches comment finira la chose, car cet homme ne se donnera point de repos qu'il n'ait terminé cette affaire aujourd'hui.
4:1\tBoaz went to the town gate and took a seat there. Just then the family redeemer he had mentioned came by, so Boaz called out to him, “Come over here and sit down, friend. I want to talk to you.” So they sat down together.\tBoaz monta à la porte, et s'y arrêta. Or voici, celui qui avait droit de rachat, et dont Boaz avait parlé, vint à passer. Boaz lui dit: Approche, reste ici, toi un tel. Et il s'approcha, et s'arrêta.
4:2\tThen Boaz called ten leaders from the town and asked them to sit as witnesses.\tBoaz prit alors dix hommes parmi les anciens de la ville, et il dit: Asseyez-vous ici. Et ils s'assirent.
4:3\tAnd Boaz said to the family redeemer, “You know Naomi, who came back from Moab. She is selling the land that belonged to our relative Elimelech.\tPuis il dit à celui qui avait le droit de rachat: Naomi, revenue du pays de Moab, a vendu la pièce de terre qui appartenait à notre frère Élimélec.
4:4\tI thought I should speak to you about it so that you can redeem it if you wish. If you want the land, then buy it here in the presence of these witnesses. But if you don’t want it, let me know right away, because I am next in line to redeem it after you.” The man replied, “All right, I’ll redeem it.”\tJ'ai cru devoir t'en informer, et te dire: Acquiers-la, en présence des habitants et en présence des anciens de mon peuple. Si tu veux racheter, rachète; mais si tu ne veux pas, déclare-le-moi, afin que je le sache. Car il n'y a personne avant toi qui ait le droit de rachat, et je l'ai après toi. Et il répondit: je rachèterai.
4:5\tThen Boaz told him, “Of course, your purchase of the land from Naomi also requires that you marry Ruth, the Moabite widow. That way she can have children who will carry on her husband’s name and keep the land in the family.”\tBoaz dit: Le jour où tu acquerras le champ de la main de Naomi, tu l'acquerras en même temps de Ruth la Moabite, femme du défunt, pour relever le nom du défunt dans son héritage.
4:6\t“Then I can’t redeem it,” the family redeemer replied, “because this might endanger my own estate. You redeem the land; I cannot do it.”\tEt celui qui avait le droit de rachat répondit: Je ne puis pas racheter pour mon compte, crainte de détruire mon héritage; prends pour toi mon droit de rachat, car je ne puis pas racheter.
4:7\tNow in those days it was the custom in Israel for anyone transferring a right of purchase to remove his sandal and hand it to the other party. This publicly validated the transaction.\tAutrefois en Israël, pour valider une affaire quelconque relative à un rachat ou à un échange, l'un ôtait son soulier et le donnait à l'autre: cela servait de témoignage en Israël.
4:8\tSo the other family redeemer drew off his sandal as he said to Boaz, “You buy the land.”\tCelui qui avait le droit de rachat dit donc à Boaz: Acquiers pour ton compte! Et il ôta son soulier.
4:9\tThen Boaz said to the elders and to the crowd standing around, “You are witnesses that today I have bought from Naomi all the property of Elimelech, Kilion, and Mahlon.\tAlors Boaz dit aux anciens et à tout le peuple: Vous êtes témoins aujourd'hui que j'ai acquis de la main de Naomi tout ce qui appartenait à Élimélec, à Kiljon et à Machlon,
4:10\tAnd with the land I have acquired Ruth, the Moabite widow of Mahlon, to be my wife. This way she can have a son to carry on the family name of her dead husband and to inherit the family property here in his hometown. You are all witnesses today.”\tet que je me suis également acquis pour femme Ruth la Moabite, femme de Machlon, pour relever le nom du défunt dans son héritage, et afin que le nom du défunt ne soit point retranché d'entre ses frères et de la porte de son lieu. Vous en êtes témoins aujourd'hui!
4:11\tThen the elders and all the people standing in the gate replied, “We are witnesses! May the Lord make this woman who is coming into your home like Rachel and Leah, from whom all the nation of Israel descended! May you prosper in Ephrathah and be famous in Bethlehem.\tTout le peuple qui était à la porte et les anciens dirent: Nous en sommes témoins! Que l'Éternel rende la femme qui entre dans ta maison semblable à Rachel et à Léa, qui toutes les deux ont bâti la maison d'Israël! Manifeste ta force dans Éphrata, et fais-toi un nom dans Bethléhem!
4:12\tAnd may the Lord give you descendants by this young woman who will be like those of our ancestor Perez, the son of Tamar and Judah.”\tPuisse la postérité que l'Éternel te donnera par cette jeune femme rendre ta maison semblable à la maison de Pérets, qui fut enfanté à Juda par Tamar!
4:13\tSo Boaz took Ruth into his home, and she became his wife. When he slept with her, the Lord enabled her to become pregnant, and she gave birth to a son.Boaz prit Ruth, qui devint sa femme, et il alla vers elle. L'Éternel permit à Ruth de concevoir, et elle enfanta un fils.
4:14\tThen the women of the town said to Naomi, “Praise the Lord, who has now provided a redeemer for your family! May this child be famous in Israel.\tLes femmes dirent à Naomi: Béni soit l'Éternel, qui ne t'a point laissé manquer aujourd'hui d'un homme ayant droit de rachat, et dont le nom sera célébré en Israël!
4:15\tMay he restore your youth and care for you in your old age. For he is the son of your daughter-in-law who loves you and has been better to you than seven sons!”\tCet enfant restaurera ton âme, et sera le soutien de ta vieillesse; car ta belle-fille, qui t'aime, l'a enfanté, elle qui vaut mieux pour toi que sept fils.
4:16\tNaomi took the baby and cuddled him to her breast. And she cared for him as if he were her own.\tNaomi prit l'enfant et le mit sur son sein, et elle fut sa garde.
4:17\tThe neighbor women said, “Now at last Naomi has a son again!” And they named him Obed. He became the father of Jesse and the grandfather of David.\tLes voisines lui donnèrent un nom, en disant: Un fils est né à Naomi! Et elles l'appelèrent Obed. Ce fut le père d'Isaï père de David.
4:18\tThis is the genealogical record of their ancestor Perez:  Perez was the father of Hezron.\tVoici la postérité de Pérets. Pérets engendra Hetsron;
4:19\tHezron was the father of Ram. Ram was the father of Amminadab.\tHetsron engendra Ram; Ram engendra Amminadab;
4:20\tAmminadab was the father of Nahshon. Nahshon was the father of Salmon.\tAmminadab engendra Nachschon; Nachschon engendra Salmon;
4:21\tSalmon was the father of Boaz. Boaz was the father of Obed.\tSalmon engendra Boaz; Boaz engendra Obed;
4:22\tObed was the father of Jesse. Jesse was the father of David.\tObed engendra Isaï; et Isaï engendra David.`;

export default bibles;
